com:
  firstboot:
    web:
      name: 程序员大哥
      title: Spring Boot练习
      desc: ${com.firstboot.web.name}正在写${com.firstboot.web.title}
      value: ${random.value}
      number: ${random.int}
      bignumber: ${random.long}
      test1: ${random.int(10)}
      test2: ${random.int[10,20]}

server:
  port: 8888
spring:
  profiles:
    active: test
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: create
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect